package:
  name: geograpy
  version: "0.3.7"

source:
  git_url: https://github.com/zcarwile/geograpy.git

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - geograpy = geograpy:main
    #
    # Would create an entry point called geograpy that calls geograpy.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy
    - nltk
    - jellyfish
    - pycountry

  run:
    - python
    - numpy
    - nltk
    - jellyfish
    - pycountry

test:
  # Python imports
  imports:
    - geograpy

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/ushahidi/geograpy
  license: MIT
  summary: 'Extract countries, regions and cities from a URL or text'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
